# Header
menu:
	Home: /
	Archives: /archives
  Categories: /categories
	Tags: /tags
	Github: https://github.com/owlikesj/hexoblog

# Masthead image
header_bg: img/header.jpg

# Sidebar
widgets:
- category
- tagcloud
- about