# Header
menu:
	Home: /
	Archives: /archives
	Tags: /tags
	Categories: /categories
	Github: https://github.com/owlikesj/hexoblog

# Masthead image
header_bg: img/header.jpg

# Sidebar
widgets:
- category
- tagcloud
- about